version: '3.8'

services:
  notification-service:
    build: .
    container_name: notification-service
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true
