version: '3.8'

services:
  catalog-service:
    build:
      context: .
    container_name: catalog-service
    restart: always
    ports:
      - "8001:8000"
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: ecommerce-mysql  
      DB_PORT: 3306
      DB_DATABASE: ecommerce
      DB_USERNAME: ecommerce
      DB_PASSWORD: ecommerce
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true
